### ISSUE TITLE
WithdrawalManager should be able to track balances for a lender, and allow him to withdraw his share of repayments

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-contracts#25]

**Comment by adibas03** [comment]
`RepaymentRouter` presently receives repayment from `borrower` as well as manages withdrawal to the `lenders`. Do we want to separate the functionality?

**Comment by onggunhao** [comment]
@adibas03 - I think we should go with what is simplest. I created this task more to cover functionality, not the actual contract name

**Comment by onggunhao** [comment]
Completed
