### ISSUE TITLE
Create a mock ERC20 Dai token on Ganache testnet for testing purposes

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-contracts#26]

**Comment by adibas03** [comment]
@onggunhao could you explain this better?
Should the DAI token be deployed to Ganache or Kovan?

**Comment by tspoff** [comment]
I think we'd be fine with a generic TestDai token on Ganache if it isn't easy to get the Dai ecosystem deployed & initialized.

**Comment by onggunhao** [comment]
I briefly browsed the MakerDAO repo and saw there was a repo for integrating Dai on Ganache
https://makerdao.com/documentation/#developing

**Comment by adibas03** [comment]
We have a generic ERC20 contract implemented in #36 
If, that's enough, this can be closed once it is merged

**Comment by onggunhao** [comment]
Got it - let's merge that
