### ISSUE TITLE
User error in sending funds

### ISSUE THREAD

**Issue by tspoff** [enabledao/enable-contracts#32]
This is related to the inherent issue of ERC20 tokens that there is no way to know if someone has sent them to a contract on-chain (no hooks) and no way to react when this happens.

(Aside: Maybe some sort of event log + proof could exist to solve this... Hopefully tokens with hooks become the standard)

#### Situation 1: Borrower sends payment tokens natively to RepaymentRouter
- We don't want to allow the user to withdraw tokens because this contract stores tokens for others! Otherwise we could have an onlyBorrower() method that allows approval + transfer from the contract.

#### Situation 2: Borrower sends payment tokens natively to incorrect contract
- If they use the UI, this won't happen

#### Situation 3: Lenders make native token transfers to Crowdsale
- If they use the UI, this won't happen
- Funds are often lost this way IRL

#### Situation 4: Someone sends Eth somewhere
- All contracts will have fallback functions that revert() to prevent accidental Eth sends

**Comment by onggunhao** [comment]
For Situation (1) and (2), I think we can hand-hold @wimanesti as she goes through the repayment process. I do think she can
* Buy on coinbase
* Transfer to Metamask (or use the Coinbase wallet)
* Repay the loan

For Situation (3), it seems like this is the curse of ERC20. I don't think Dai is moving to ERC777 anytime soon?

I think the fallback functions are wise
