### ISSUE TITLE
RepaymentManager - Missing functions

### ISSUE THREAD

**Issue by adibas03** [enabledao/enable-contracts#45]
Track missing features from components
-  [x] Trigger TermsContract to do a loanStatus update after each payment/ withdrawal.
- [ ] Optimize `payee` variable within the contract: Either remove completely or optimize to be usable.

**Comment by onggunhao** [comment]
As per discussion in Discord, we also need a way to track past repayments, to determine whether or not a loan is in default.

* One possible strategy is to keep a array of repayments (timestamp, amount). We juxtapose this with the `TermsContract` `getScheduledPayments` to determine whether a loan is in default.

* Another possible strategy (as suggested by @adibas03) is to track the repayment number that has been paid, and use event logs to determine 

From a financial angle, the `timestamps` of repayments matter a lot for calculating penalties. E.g. if someone pays 300 but 7 months after the fact, it incurs additional interest on the 7 late months.

**Comment by adibas03** [comment]
So,
To know if a repayment is in default,
all we need are:  `activeTranch`, `secondsPerTranch`, which can be used to calculate the expectedRepayment timestamp: (`(activeTranch+1)secondsPerTranch`), add gracePeriod and we have a value to compare to `now`.
so, a payment coming 7 months later will have `now > expectedRepaymentTimestamp`, which will be 7 months in excess

**Comment by onggunhao** [comment]
@adibas03 I think we already have that in the `scheduledPayments`, see:

`getScheduledPayments(tranche)`: https://github.com/enabledao/enable-contracts/blob/f6dbe515c3f5450284927df988db3110af2e437c/contracts/debt-contracts/TermsContract.sol#L115

`getExpectedRepaymentValue(timestamp)`: https://github.com/enabledao/enable-contracts/blob/f6dbe515c3f5450284927df988db3110af2e437c/contracts/debt-contracts/TermsContract.sol#L170
