### ISSUE TITLE
Crowdloan contract - Missing functions

### ISSUE THREAD

**Issue by adibas03** [enabledao/enable-contracts#46]
Track missing functions in crowdloan contract
- Implement crowdloanEnd (Time trigger to end crowdfund period)
- Set time to wait between crowdfund completion and withdrawal, after which lenders can refund their loans if the borrower did not start the loan (Prevents bad borrower holding lenders funds hostage, might be pointless)

**Comment by onggunhao** [comment]
@adibas03 I think the 2nd one should be KIV-ed to the next fundraise, with the goal of keeping things as simple as possible for Ines' fundraise
