### ISSUE TITLE
Remove ability to ask for refunds

### ISSUE THREAD

**Issue by onggunhao** [enabledao/enable-contracts#50]
**High-level spec**:

* To simplify the smart contracts, we are not going to allow for refunds (at least for Ines.fund) during crowdfunding phase
* We can explore starting loan status once contract is deployed, to reduce the attack surface there as well
* We may **still** need refunds for the scenario where funding is done, but borrower wants to cancel the loan

**Comment by adibas03** [comment]
The immediate starting of the loan, can be taken care of by setting the crowdfund Start time when deploying the contract
