### ISSUE TITLE
Add a function that return the number of payees on the Repayment Manager contract

### ISSUE THREAD

**Issue by djuanit0x** [enabledao/enable-contracts#61]
The current payess on Repayment Manager contract is a private state; thus, it's difficult to retrieve from the front end.

See here https://github.com/enabledao/enable-contracts/blob/7faa5914d65a2e7dc06bb24d7922d7d2c16eb054/contracts/debt-contracts/RepaymentManager.sol#L20

**Comment by onggunhao** [comment]
@djuanit0x It's actually been removed - we actually thought that we could use the `fund` event to get the list of lenders. 

https://ethereum.stackexchange.com/a/22882/53966

https://github.com/enabledao/enable-contracts/blob/6f9b8b6cc8e8a66488c418fca326d3aa3702d46b/contracts/crowdloan/Crowdloan.sol#L132
