### ISSUE TITLE
Repayment Allocation Tracking 

### ISSUE THREAD

**Issue by tspoff** [enabledao/enable-contracts#7]
## Issue
Tracking what lenders are entitled to withdraw what repayments at what time requires overhead. We want to minimize cost and keep interfaces as familiar as possible.

### MiniMe Style ERC-20
[+] Can handle ERC-20 payment tokens if sent though a function, like repay()

[-] O(logn) loops on transfer and withdraw
[-] Large storage overhead

**Conclusion**: Likely won't use due to gas costs

### ERC-721
[+] Can handle ERC-20 payment tokens if sent though a function, like repay()
[+] No loops, withdraws simple to calculate

[-] Can't split or combine stake without extra logic
[-] Can't withdraw multiple stakes at once without a batch function (which we could totally do)

### ERC-1843: Claims Token Standard
[+] Can keep ERC-20 ownership tokens, looks efficient (still evaluating)

[-] Requires payment token to be ERC-223 compatible for the tokenFallback hook.
    * We could potentially "wrap" the payment token before sending, it'd be the same number 
    of calls as approve() + function() anyways.

### ERC-1726: Dividend-Paying Token Standard
[-] Only supports Ether payments

**Conclusion**: Won't use as ERC-20 payments are critical. Can learn from though.

**Comment by adibas03** [comment]
@tspoff you should add links

**Comment by onggunhao** [comment]
Discussion is repeated at https://github.com/enabledao/enable/issues/99
